### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

### ISSUE THREAD

**Issue by dukebody** [scobal/seyren#253]
I've configured Seyren to pull metrics from Graphite. 

It works at first, but after some time (like 1-2 days) it stops being able to read from Graphite and all figures appear broken. The "Last check" for many enabled checks gets stuck in an old time. If I restart seyren everything starts working again.

My Graphite instance is behind HTTP authentication but I've set GRAPHITE_USERNAME and GRAPHITE_PASSWORD accordingly (and it works after seyren is restarted).

I run seyren using:
    exec java -jar /home/ubuntu/build/seyren/seyren-1.2.0.jar -httpPort=8081

Tail from the logs:

``` code
26/11/2014 16:31:46.916 [http-bio-8081-exec-7] WARN   c.s.c.s.c.GraphiteTargetChecker - integral(transformNull(stats.counters.lr-prod.leads.view.leadrating.promof.count, 0)) failed to read from Graphite
 com.seyren.core.util.graphite.GraphiteReadException: Failed to read from Graphite
        at com.seyren.core.util.graphite.GraphiteHttpClient.getTargetJson(GraphiteHttpClient.java:136) ~[seyren-core-1.2.0.jar:na]
        at com.seyren.core.service.checker.GraphiteTargetChecker.check(GraphiteTargetChecker.java:50) ~[seyren-core-1.2.0.jar:na]
        at com.seyren.api.bean.MetricsBean.totalMetric(MetricsBean.java:42) [seyren-api-1.2.0.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [seyren-1.2.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [seyren-1.2.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [seyren-1.2.0.jar:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [seyren-1.2.0.jar:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [seyren-1.2.0.jar:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [seyren-1.2.0.jar:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [seyren-1.2.0.jar:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [seyren-1.2.0.jar:na]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [seyren-1.2.0.jar:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [seyren-1.2.0.jar:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [seyren-1.2.0.jar:na]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [seyren-1.2.0.jar:na]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [seyren-1.2.0.jar:na]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [seyren-1.2.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@72e00409; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524) ~[jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557) ~[jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475) ~[jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2342) ~[jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:817) ~[jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697) ~[jackson-core-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3031) ~[jackson-databind-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2978) ~[jackson-databind-2.3.2.jar:2.3.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1737) ~[jackson-databind-2.3.2.jar:2.3.2]
        at com.seyren.core.service.checker.JsonNodeResponseHandler.handleResponse(JsonNodeResponseHandler.java:37) ~[seyren-core-1.2.0.jar:na]
        at com.seyren.core.service.checker.JsonNodeResponseHandler.handleResponse(JsonNodeResponseHandler.java:28) ~[seyren-core-1.2.0.jar:na]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) ~[httpclient-4.3.3.jar:4.3.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[httpclient-4.3.3.jar:4.3.3]
        at com.seyren.core.util.graphite.GraphiteHttpClient.getTargetJson(GraphiteHttpClient.java:134) ~[seyren-core-1.2.0.jar:na]
        ... 32 common frames omitted
```

Any clues?

**Comment by MartinNowak** [comment]
> To me, it looks like Seyren loses the ability to authenticate using GRAPHITE_USERNAME and GRAPHITE_PASSWORD after some time, then Graphite returns a HTML Unauthorized, which Seyren can't parse as JSON.

I have the same symptoms here, after some time Seyren "forgets" the basic auth credentials.
This even happens when I add them in the URL (https://user@password:domain/graphite/) instead of passing them as separate env variables.

**Comment by MartinNowak** [comment]
Looks like the username and password get corrupted before they are forgotten (username starts w/ a few chars from the PW ending, or is just a slice of the username).

**Comment by shortdudey123** [comment]
@MartinNowak seeing the same thing, username or password doesn't get sent in its entirety.  Did you figure out what was happening? been seeing this for a while now

Version `1.4.0`
Basic auth via nginx (as opposed to apache which was mentioned earlier)
