### ISSUE TITLE
Cannot Edit/Delete Check

### ISSUE THREAD

**Issue by chriscannon** [scobal/seyren#276]
Hello,

I'm having an issue with Seyren where I cannot edit or delete existing checks (I can however add new checks). When I go to delete a check and click the "Ok" button on the "Are you sure?" dialog I see an error popup in the window saying, "Sorry, Seyren or Graphite are not available". This was working at some point, then suddenly stopped working. Both Graphite and Seyren are running on the same machine. I tried restarting the seyren and mongod services, but it did not help. I am running Seyren version 1.2.1.

**Comment by obazoud** [comment]
is there exceptions in seyren log ?

**Comment by chriscannon** [comment]
There's many exceptions in seyren.log, but they are all just warnings. Here's the only relevant one I see

```
 05/04/2015 00:46:58.325 [qtp1391560582-45] WARN   c.s.c.s.c.GraphiteTargetChecker - pubdash_stats.prod.gauges.pub_metrics.replication_delay failed to read from Graphite
 com.seyren.core.exception.InvalidGraphiteValueException: Could not find a valid datapoint for target: "pubdash_stats.prod.gauges.pub_metrics.replication_delay"
        at com.seyren.core.service.checker.GraphiteTargetChecker.getLatestValue(GraphiteTargetChecker.java:83) ~[seyren-core-1.2.1.jar:na]
        at com.seyren.core.service.checker.GraphiteTargetChecker.check(GraphiteTargetChecker.java:54) ~[seyren-core-1.2.1.jar:na]
        at com.seyren.api.bean.MetricsBean.totalMetric(MetricsBean.java:42) [seyren-api-1.2.1.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_72]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_72]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.6.Final.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.handle(Server.java:445) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-runner.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-runner.jar:9.0.5.v20130815]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
```

**Comment by chriscannon** [comment]
Any ideas?

**Comment by obazoud** [comment]
As I can see in [source code](https://github.com/scobal/seyren/blob/1.2.1/seyren-core/src/main/java/com/seyren/core/service/checker/GraphiteTargetChecker.java#L83), Seyren gets JSON data but all values are null.

**Comment by chriscannon** [comment]
What does that have to do with editing/deleting checks?

**Comment by obazoud** [comment]
is there something interesting in browser log ?

**Comment by chriscannon** [comment]
Upgrading to 1.3.0 solved this issue.

**Comment by gargnisha1605** [comment]
Following are the logs formed: 
Can anyone suggest how to resolve this?

[seyren.check-scheduler-2] WARN   c.s.c.service.schedule.CheckRunner - No value present for Fail
 09/02/2017 16:44:53.516 [seyren.check-scheduler-0] WARN   c.s.c.s.c.GraphiteTargetChecker - {"target":"REQUEST_FAILED","datapoints":[[null,1486638240],[null,1486638300],[null,1486638360],[null,1486638420],[null,1486638480],[null,1486638540],[null,1486638600],[null,1486638660],[null,1486638720],[null,1486638780]]}
[seyren.check-scheduler-0] WARN   c.s.c.s.c.GraphiteTargetChecker -  REQUEST FAILURE failed to read from Graphite
 com.seyren.core.exception.InvalidGraphiteValueException: Could not find a valid datapoint for target: "REQUEST_FAILED"
    at com.seyren.core.service.checker.GraphiteTargetChecker.getLatestValue(GraphiteTargetChecker.java:83) ~[seyren-core-1.0.1-SNAPSHOT.jar:na]
    at com.seyren.core.service.checker.GraphiteTargetChecker.check(GraphiteTargetChecker.java:54) ~[seyren-core-1.0.1-SNAPSHOT.jar:na]
    at com.seyren.core.service.schedule.CheckRunner.run(CheckRunner.java:65) ~[seyren-core-1.0.1-SNAPSHOT.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.6.0_30]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.6.0_30]
    at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.6.0_30]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165) ~[na:1.6.0_30]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266) ~[na:1.6.0_30]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) ~[na:1.6.0_30]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.6.0_30]
    at java.lang.Thread.run(Thread.java:701) ~[na:1.6.0_30]
 [seyren.check-scheduler-0] WARN   c.s.c.service.schedule.CheckRunner - No value present for REQUEST_FAILED
