### ISSUE TITLE
Unable to setup HTTP Subscription Type

### ISSUE THREAD

**Issue by dheerajpanyam** [scobal/seyren#311]
I am trying to setup a HTTP subscription type but it is failing with the below error message.

 I am running Graphite , seyren on the same local server with different ports and i am able to see the alerts , graphs in graphite etc no issues on that front. Data to graphite for now is produced using patterns configured in Graphite.

Graphite running on default port 80
Seyren running on port 8081
HTTP subscription type configured to run on port 8888 which is not working 

23/06/2015 14:59:59.502 [http-bio-8081-exec-8] WARN   c.seyren.api.bean.SubscriptionsBean - Notifying http://xxx.xxx.xxx.xxx:8888 by HTTP failed.
 com.seyren.core.exception.NotificationFailedException: Failed to send notification to HTTP
        at com.seyren.core.service.notification.HttpNotificationService.sendNotification(HttpNotificationService.java:89) ~[seyren-core-1.3.0.jar:na]
        at com.seyren.api.bean.SubscriptionsBean.testSubscription(SubscriptionsBean.java:106) ~[seyren-api-1.3.0.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.10.Final.jar:na]

**Comment by obazoud** [comment]
Works fine here.
I start Seyren with Docker Compose:

```
% docker-compose up
```
with the following diff.
```diff
+    HTTP_NOTIFICATION_URL: http://localhost:8888
+    SEYREN_LOG_FILE_LEVEL: INFO
+    console.log.level: INFO
```

I start a shell on seyren web docker container

```shell
% docker exec -it xxxxx /bin/bash
```
And I write a little python script.
```python
#!/usr/bin/python
import socket
 
HOST = '127.0.0.1'
PORT = 8888
 
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(1)
conn, addr = s.accept()
print 'Connected by', addr
while 1:
    data = conn.recv(1024)
    if not data: break
    conn.send(data)
conn.close()
```
I can start this script.
As you can see, Seyren posts data to this specified URL.

```
root@xxxx:/data# python echo.py
Connected by ('127.0.0.1', 42154)
Data:  POST / HTTP/1.1
Content-Length: 1405
Content-Type: application/json; charset=UTF-8
Host: localhost:8888
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
Accept-Encoding: gzip,deflate

{"alerts":[{"id":"5592abcce4b0257982613639","checkId":"55929e62e4b0ce9df551aed7","value":1.26,"target":"collectd.sample.load.load.longterm","warn":0.1,"error":0.3,"fromType":"OK","toType":"ERROR","timestamp":1435675596318,"targetHash":"\t%|d������x��-J"}],"preview":"<br /><img src=http://graphite/render/?target=collectd.sample.load.load.longterm&from=14:46_20150630&until=13:46_20150630&target=alias(dashed(color(constantLine(0.1),%22yellow%22)),%22warn%20level%22)&target=alias(dashed(color(constantLine(0.3),%22red%22)),%22error%20level%22)&width=500&height=225></img>","seyrenUrl":"http://localhost:8080/seyren","check":{"id":"55929e62e4b0ce9df551aed7","name":"xxxx","description":null,"target":"collectd.sample.load.load.longterm","from":null,"until":null,"warn":"0.1","error":"0.3","enabl
Data:  ed":true,"live":false,"allowNoData":false,"state":"ERROR","lastCheck":1435675596322,"subscriptions":[{"id":"55929e7be4b0ce9df551aed8","target":"xxx","type":"HTTP","su":true,"mo":true,"tu":true,"we":true,"th":true,"fr":true,"sa":true,"ignoreWarn":false,"ignoreError":false,"ignoreOk":false,"fromTime":"0000","toTime":"2359","enabled":true}]},"subscription":{"id":"55929e7be4b0ce9df551aed8","target":"xxx","type":"HTTP","su":true,"mo":true,"tu":true,"we":true,"th":true,"fr":true,"sa":true,"ignoreWarn":false,"ignoreError":false,"ignoreOk":false,"fromTime":"0000","toTime":"2359","enabled":true}}
...
```

**Comment by dheerajpanyam** [comment]
Thanks Olivier Bazoud, yes it is working fine for me too. I am a newbie to Graphite and Seyren , it was not working because the target was not configured in the correct format ( is there one by the way) but i was see the alerts etc showing in the Seyren Dashboard but the HTTP subscription somehow didn't accept that target, thanks much again

**Comment by dheerajpanyam** [comment]
Hello Olivier sorry to bother you again .. I am interested in fetching data to one of the HTTP subscription URLs that Seyren is outputing. I  have configured it to be port 8889 on my local machine , graphite and seyren are also running on same machine on different ports.

I would like to retrieve data from the form which is a  CgiFieldStorageInstance, ( shown below) would like to get all the alerts.

Thanks in advance and appreciate your help

Regards
Dheeraj


class ServerHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):

    def do_GET(self):
        logging.warning("======= GET STARTED =======")
        logging.warning(self.headers)
        SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)

    def do_POST(self):
        logging.warning("======= POST STARTED =======")
        logging.warning(self.headers)
        form = cgi.FieldStorage(
            fp=self.rfile,
            headers=self.headers,
            environ={'REQUEST_METHOD':'POST',
                     'CONTENT_TYPE':self.headers['Content-Type'],
                     })
        logging.warning("======= POST VALUES =======")
        logging.warning(form)
        logging.warning("\n")
        SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)

Handler = ServerHandler

httpd = SocketServer.TCPServer(("", PORT), Handler)
