### ISSUE TITLE
Could Not Find Resource For Full Path

### ISSUE THREAD

**Issue by chriscannon** [scobal/seyren#318]
Hello,

I recently upgraded Seyren from 1.1.0 to 1.3.0 and now cannot view my alerts and Seyren shows me the error message "Sorry, Seyren or Graphite are not available.". I'm running Seyren from the 1.3.0 JAR. The only thing I notice in the Seyren logs are this:

```
30/06/2015 23:14:36.307 [http-bio-9081-exec-9] WARN   o.j.resteasy.core.ExceptionHandler - failed to execute
 javax.ws.rs.NotFoundException: Could not find resource for full path: http://domain.com//api/alerts?items=10
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:112) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:444) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:234) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:171) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.10.Final.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [seyren-1.2.1.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [seyren-1.2.1.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [seyren-1.2.1.jar:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [seyren-1.2.1.jar:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [seyren-1.2.1.jar:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [seyren-1.2.1.jar:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [seyren-1.2.1.jar:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [seyren-1.2.1.jar:na]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [seyren-1.2.1.jar:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [seyren-1.2.1.jar:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [seyren-1.2.1.jar:na]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [seyren-1.2.1.jar:na]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [seyren-1.2.1.jar:na]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [seyren-1.2.1.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```

I can also see errors in the Graphite log:

```
[Wed Jul 01 14:46:42 2015] [error] [client xxx.xxx.xxx.xxx] (104)Connection reset by peer: proxy: error reading status line from remote server localhost:9081, referer: http://domain.com/seyren/
[Wed Jul 01 14:46:42 2015] [error] [client xxx.xxx.xxx.xxx] proxy: Error reading from remote server returned by /seyren/api/checks, referer: http://domain.com/seyren/
```

I know that mongo is running and that I can see the alerts in the `seyren` database. I know that graphite is running and still collecting data. What strange is I tried to upgrade and failed with this error. Then I rolled  back to the 1.1.0 JAR and I still get the same error message that Seyren or Graphite is not available and the same "Could not find resource for full path". This is mind boggling because it's the exact same code and configuration that worked before except now it does not work. If you have any ideas why this is happening it would be greatly appreciated.

**Comment by chriscannon** [comment]
The only other error I noticed is that `http://domain.com//api/alerts?items=10` has an extra `/`. This is really strange because the config only specifies one `/` and the config has not changed from when it was working to when it is not working.

**Comment by chriscannon** [comment]
Also even though I'm using `http://localhost:80` in my config, it's showing up as `http://domain.com` in the logs...

**Comment by chriscannon** [comment]
I found a couple more errors while running the `master` branch in `debug` log level:

```
 01/07/2015 20:09:18.254 [localhost-startStop-1] DEBUG  o.s.s.a.ScheduledAnnotationBeanPostProcessor - Could not find default TaskScheduler bean
 org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.scheduling.TaskScheduler] is defined
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371) [spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) [spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.afterSingletonsInstantiated(ScheduledAnnotationBeanPostProcessor.java:157) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:782) [spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.jboss.resteasy.plugins.spring.SpringContextLoaderListener.contextInitialized(SpringContextLoaderListener.java:48) [resteasy-spring-3.0.10.Final.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5291) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```
```
01/07/2015 20:09:18.255 [localhost-startStop-1] DEBUG  o.s.s.a.ScheduledAnnotationBeanPostProcessor - Could not find default ScheduledExecutorService bean
 org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.scheduling.TaskScheduler] is defined
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371) [spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) [spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.afterSingletonsInstantiated(ScheduledAnnotationBeanPostProcessor.java:157) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:782) [spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) [spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.jboss.resteasy.plugins.spring.SpringContextLoaderListener.contextInitialized(SpringContextLoaderListener.java:48) [resteasy-spring-3.0.10.Final.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5291) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) [seyren-web-1.4.0-SNAPSHOT-war-exec.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```

```
 01/07/2015 20:09:18.555 [seyren.check-scheduler-2] WARN   c.s.c.s.c.GraphiteTargetChecker - 50 Graphite High Load failed to read from Graphite
 com.seyren.core.util.graphite.GraphiteReadException: Failed to read from Graphite
        at com.seyren.core.util.graphite.GraphiteHttpClient.getTargetJson(GraphiteHttpClient.java:136) ~[seyren-core-1.4.0-SNAPSHOT.jar:na]
        at com.seyren.core.service.checker.GraphiteTargetChecker.check(GraphiteTargetChecker.java:50) ~[seyren-core-1.4.0-SNAPSHOT.jar:na]
        at com.seyren.core.service.schedule.CheckRunner.run(CheckRunner.java:65) [seyren-core-1.4.0-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_05]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_05]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@34f14ea5; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486) ~[jackson-core-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[jackson-core-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447) ~[jackson-core-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2486) ~[jackson-core-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801) ~[jackson-core-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697) ~[jackson-core-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600) ~[jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545) ~[jackson-databind-2.5.0.jar:2.5.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2074) ~[jackson-databind-2.5.0.jar:2.5.0]
        at com.seyren.core.service.checker.JsonNodeResponseHandler.handleResponse(JsonNodeResponseHandler.java:37) ~[seyren-core-1.4.0-SNAPSHOT.jar:na]
        at com.seyren.core.service.checker.JsonNodeResponseHandler.handleResponse(JsonNodeResponseHandler.java:28) ~[seyren-core-1.4.0-SNAPSHOT.jar:na]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) ~[httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[httpclient-4.3.6.jar:4.3.6]
        at com.seyren.core.util.graphite.GraphiteHttpClient.getTargetJson(GraphiteHttpClient.java:134) ~[seyren-core-1.4.0-SNAPSHOT.jar:na]
        ... 9 common frames omitted
```

**Comment by chriscannon** [comment]
I even tried dropping out the seyren mongodb collection and it still says Seyren or Graphite is not available.

**Comment by obazoud** [comment]
In your case, I think that Graphite returns html and not json.
```
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
```
Could you try to get value from Graphite with curl (for example) ?

**Comment by chriscannon** [comment]
Should the `/api/alerts?items=10` route be hitting graphite or seyren?

**Comment by scobal** [comment]
I'm going to close this but please re-open if you're still using Seyren and having this issue

**Comment by chriscannon** [comment]
Honestly Seyren had so many bugs and was so unreliable that our company just switched to using DataDog.

**Comment by scobal** [comment]
Thanks for letting me know @chriscannon. Those guys have definitely got the right idea of getting paid to do this!
