### ISSUE TITLE
Running seyren on ubuntu 16.04

### ISSUE THREAD

**Issue by kgoedert** [scobal/seyren#399]
Hi,

I am trying to run seyren on a ubuntu 16.04, with java 8 and mongodb 3.2.8. When I start seyren I get the following error:

```
/opt/seyren$ sudo java -jar seyren-1.3.0.jar -httpPort=8081
ago 15, 2016 12:35:24 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8081"]
ago 15, 2016 12:35:24 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
ago 15, 2016 12:35:24 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.37
ago 15, 2016 12:35:30 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
ago 15, 2016 12:35:31 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
ago 15, 2016 12:35:32 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.jboss.resteasy.plugins.spring.SpringContextLoaderListener
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'subscriptionsBean' defined in URL [jar:file:/opt/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-api-1.3.0.jar!/com/seyren/api/bean/SubscriptionsBean.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.seyren.core.store.ChecksStore]: : Error creating bean with name 'mongoStore' defined in URL [jar:file:/opt/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.3.0.jar!/com/seyren/mongo/MongoStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoStore' defined in URL [jar:file:/opt/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.3.0.jar!/com/seyren/mongo/MongoStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1131)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1034)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.jboss.resteasy.plugins.spring.SpringContextLoaderListener.contextInitialized(SpringContextLoaderListener.java:48)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5291)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoStore' defined in URL [jar:file:/opt/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.3.0.jar!/com/seyren/mongo/MongoStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1131)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1034)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 25 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 38 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
	at com.seyren.mongo.MongoStore.<init>(MongoStore.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 40 more
Caused by: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
	at com.seyren.mongo.MongoStore.bootstrapMongo(MongoStore.java:89)
	at com.seyren.mongo.MongoStore.<init>(MongoStore.java:73)
	... 45 more
Caused by: com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "nIndexesWas" : 3 , "ok" : 0.0 , "errmsg" : "index not found with name [checkId_1_target_1]" , "code" : 27}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:131)
	at com.mongodb.DBCollection.dropIndexes(DBCollection.java:1004)
	at com.mongodb.DBCollection.dropIndex(DBCollection.java:1723)
	at com.seyren.mongo.MongoStore.removeOldIndices(MongoStore.java:105)
	at com.seyren.mongo.MongoStore.bootstrapMongo(MongoStore.java:83)
	... 46 more
```

Mongo is running in the same machine with default configurations. 
What have I missed? Thanks for any help

**Comment by alenkacz** [comment]
@kgoedert hi, have you checked the log and the following things?

Failure while bootstrapping Mongo indexes.
If you've hit this problem it's possible that you have two checks which are named the same and violate an index which we've tried to add.
Please correct the problem by removing the clash.

**Comment by kgoedert** [comment]
Hi,
There were no errors on mongo logs. Just regular info messages. I have no checks. I was trying to start seyren for the first time.

**Comment by kgoedert** [comment]
Hi,
I installed version 1.4.0 of seyren and now it works.
