### ISSUE TITLE
Unable to start, mongo error

### ISSUE THREAD

**Issue by greenaar** [scobal/seyren#405]
Fresh install, tried with mongo 2.4, 2.6, 3.2.  Tried with openjdk-7 and oracle jdk 8.

On start:

Caused by: com.mongodb.MongoCommandException: Command failed with error -1: 'index not found' on server localhost:27017. The full response is { "errmsg" : "index not found", "ok" : 0.0 }

Note, this is on first run, and every run following.

**Comment by greenaar** [comment]
Full dump:
Aug 30, 2016 6:04:58 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Aug 30, 2016 6:04:58 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Aug 30, 2016 6:04:58 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.37
Aug 30, 2016 6:05:05 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Aug 30, 2016 6:05:06 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Aug 30, 2016 6:05:07 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.jboss.resteasy.plugins.spring.SpringContextLoaderListener
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chartsBean' defined in URL [jar:file:/opt/seyren/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-api-1.4.0.jar!/com/seyren/api/bean/ChartsBean.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.seyren.core.store.ChecksStore]: : Error creating bean with name 'mongoStore' defined in URL [jar:file:/opt/seyren/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.4.0.jar!/com/seyren/mongo/MongoStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoStore' defined in URL [jar:file:/opt/seyren/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.4.0.jar!/com/seyren/mongo/MongoStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1131)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1034)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.jboss.resteasy.plugins.spring.SpringContextLoaderListener.contextInitialized(SpringContextLoaderListener.java:48)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5291)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoStore' defined in URL [jar:file:/opt/seyren/seyren/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.4.0.jar!/com/seyren/mongo/MongoStore.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1131)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1034)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 25 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
        ... 38 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
        at com.seyren.mongo.MongoStore.<init>(MongoStore.java:75)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        ... 40 more
Caused by: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
        at com.seyren.mongo.MongoStore.bootstrapMongo(MongoStore.java:89)
        at com.seyren.mongo.MongoStore.<init>(MongoStore.java:73)
        ... 45 more
Caused by: com.mongodb.MongoCommandException: Command failed with error -1: 'index not found' on server localhost:27017. The full response is { "errmsg" : "index not found", "ok" : 0.0 }
        at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:186)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:160)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:133)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:128)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:118)
        at com.mongodb.operation.DropIndexOperation.execute(DropIndexOperation.java:69)
        at com.mongodb.operation.DropIndexOperation.execute(DropIndexOperation.java:40)
        at com.mongodb.Mongo.execute(Mongo.java:781)
        at com.mongodb.Mongo$2.execute(Mongo.java:764)
        at com.mongodb.DBCollection.dropIndex(DBCollection.java:2054)
        at com.mongodb.DBCollection.dropIndex(DBCollection.java:2043)
        at com.seyren.mongo.MongoStore.removeOldIndices(MongoStore.java:105)
        at com.seyren.mongo.MongoStore.bootstrapMongo(MongoStore.java:83)
        ... 46 more

**Comment by mattadair** [comment]
As it turns out Mongo is not returning the error code 27 specified on line 107 of seyren-mongo/src/main/java/com/seyren/mongo/MongoStore.java.  Change 27 to -1 and rebuild, you'll be able to start it then.

**Comment by mattadair** [comment]
On a side note, I also suspect line 105 should actually reference "targetHash" instead of "target."

**Comment by stojg** [comment]
Confirmed, the above patch fixed it for me.

**Comment by jcampos8782** [comment]
+1 on encountering this error. Will try the above patch suggestion

**Comment by zigarn** [comment]
I encounter the same problem when upgrading from 1.3.0 to 1.5.0.
I can see that `org.mongodb.mongo-java-driver` dependency has been upgraded from `2.12.4` to `3.2.2`, so I think that using a 2.x version of MongoDB is the problem: it may not be compatible anymore.
Maybe update documentation to indicate minimal versions in requirements?
